CREATE TABLE "C##SCOTT"."NAMECARD" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"TEL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(50 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
INSERT INTO NAMECARD(ID, NAME, TEL, EMAIL, ADDRESS)VALUES INTO(AUTO_INCREMENT, '홍길동','010-3424-2432','HONG@GMAIL.COM','조선 한양 홍대감댁');
INSERT INTO NAMECARD(ID, NAME, TEL, EMAIL, ADDRESS)VALUES INTO(AUTO_INCREMENT, '김길동','010-4424-2432','HONG@GMAIL.COM','조선 한양 김대감댁');
INSERT INTO NAMECARD(ID, NAME, TEL, EMAIL, ADDRESS)VALUES INTO(AUTO_INCREMENT, '박길동','010-5424-2432','HONG@GMAIL.COM','조선 한양 박차사댁');
SELECT * FROM NAMECARD;
SELECT NAME FROM NAMECARD WHERE NAME LIKE '동%';
UPDATE NAMECARD SET NAME='전우치' WHERE NAME='김길동';
DELETE FROM NAMECARD WHERE NAME='전우치';
CREATE TABLE NAMECARD_COPY  AS SELECT * FROM NAMECARD WHERE NAME ='박길동';

DROP TABLE NAMECARD;
